groups:
  - name: flow7.rules
    rules:
      - alert: Flow7HighErrorRate
        expr: increase(flow7_requests_total{status=~"5.."}[5m]) > 5
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "High 5xx error rate for Flow7"
          description: "{{ $labels.instance }} has high 5xx errors in the last 5m."

      - alert: Flow7SchedulerDown
        expr: absent(up{job="flow7-scheduler"})
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "Scheduler process is not reporting"
          description: "Scheduler job does not appear in Prometheus 'up' metrics."

      - alert: Flow7MigrationFailed
        expr: increase(flow7_migrations_failed_total[10m]) > 0
        for: 1m
        labels:
          severity: ticket
        annotations:
          summary: "Recent migration failures detected"
          description: "Migrations have failures in the last 10 minutes. Check migration job logs."

      - alert: Flow7DBDown
        expr: increase(flow7_db_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Database errors observed by Flow7"
          description: "Flow7 has observed DB errors in the last 5 minutes. Investigate DB connectivity and credentials."

      - alert: Flow7ApschedulerJobErrors
        expr: increase(flow7_apscheduler_job_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "APScheduler job errors"
          description: "One or more scheduled jobs have failed in the last 5 minutes. Check scheduler logs and jobstore."

      - alert: Flow7HighFcmFailureRate
        expr: increase(flow7_fcm_failures_total[10m]) > 5
        for: 5m
        labels:
          severity: ticket
        annotations:
          summary: "High FCM failure rate"
          description: "Multiple FCM sends have failed in the last 10 minutes. Check Firebase credentials and token validity."
