apiVersion: batch/v1
kind: Job
metadata:
  name: flow7-smoke
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: smoke
          # use small curl image; run smoke checks against the in-cluster service
          image: curlimages/curl:8.4.0
          command: ["/bin/sh", "-c"]
          env:
            - name: SMOKE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: flow7-secrets
                  key: SMOKE_TOKEN
          args:
            - |
              set -euo pipefail
              BASE=http://flow7-web:80
              : "Using SMOKE_TOKEN from secret"
              HDR="Authorization: Bearer ${SMOKE_TOKEN}"

              echo "Checking health"
              curl -fsS ${BASE}/health

              echo "Checking metrics"
              curl -fsS ${BASE}/metrics

              echo "Waiting for readiness"
              for i in $(seq 1 60); do
                if curl -fsS ${BASE}/ready >/dev/null 2>&1; then
                  break
                fi
                sleep 1
              done

              echo "Authenticated profile"
              curl -fsS -H "${HDR}" ${BASE}/user/profile/ || (echo 'profile failed' >&2; exit 4)

              echo "Update theme"
              curl -fsS -X PUT -H "${HDR}" -H 'Content-Type: application/json' -d '{"theme":"DARK"}' ${BASE}/user/theme/

              echo "Update language"
              curl -fsS -X PUT -H "${HDR}" -H 'Content-Type: application/json' -d '{"language_code":"en"}' ${BASE}/user/language/

              echo "Update notifications"
              curl -fsS -X PUT -H "${HDR}" -H 'Content-Type: application/json' -d '{"enabled":true}' ${BASE}/user/notifications/

              echo "Create a plan"
              TODAY=$(date +%F)
              curl -fsS -X POST -H "${HDR}" -H 'Content-Type: application/json' -d "{\"date\":\"${TODAY}\",\"start_time\":\"12:00\",\"end_time\":\"12:30\",\"title\":\"smoke\",\"description\":\"smoke test\"}" ${BASE}/api/plans

              echo "List plans"
              curl -fsS -H "${HDR}" ${BASE}/api/plans

              echo 'In-cluster smoke tests passed'
      # optional: set TTL for automatic cleanup
  ttlSecondsAfterFinished: 3600
