global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Flow7 metrics via Kubernetes service
  - job_name: 'flow7'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      # select endpoints for service named "flow7-web" in any namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: flow7-web
      - source_labels: [__meta_kubernetes_endpoint_port_name, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: keep
        regex: (?:|http|metrics|web|http-metrics)
    metrics_path: /metrics

  # Fallback: scrape via cluster DNS if service discovery is not used
  - job_name: 'flow7-static'
    static_configs:
      - targets: ['flow7-web.default.svc.cluster.local:80']
    metrics_path: /metrics
