name: Docker Build & Smoke Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (load into docker)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: flow7:pr-${{ github.sha }}

      - name: Run container (smoke)
        run: |
          set -eu
          # run container in background
          docker run --rm -d --name flow7-smoke -p 8000:8000 \
            -e TESTING=1 -e DISABLE_SCHEDULER=1 -e DEV_ALLOW_CREATE_ALL=1 \
            flow7:pr-${{ github.sha }}
          # wait for health endpoint
          for i in {1..30}; do
            if curl -sS http://localhost:8000/health | grep -q '"ok":'; then
              echo "health check passed"
              break
            fi
            echo "waiting for app... ($i)"
            sleep 1
          done

      - name: Run smoke checks
        run: |
          curl -f http://localhost:8000/health
          curl -f http://localhost:8000/metrics

      - name: Stop container
        if: always()
        run: |
          docker rm -f flow7-smoke || true
