name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Postgres service for migrations
        uses: Harmon758/postgresql-action@v2
        with:
          postgresql version: '15'
          postgresql db: 'flow7'
          postgresql user: 'flow7'
          postgresql password: 'flow7'

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do pg_isready -h 127.0.0.1 -p 5432 && break || sleep 1; done

      - name: Run Alembic migrations
        env:
          DATABASE_URL: postgresql+psycopg2://flow7:flow7@127.0.0.1/flow7
        run: |
          pip install alembic
          alembic -c alembic.ini upgrade head

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check . || true

      - name: Run tests
        env:
          DATABASE_URL: postgresql+psycopg2://flow7:flow7@127.0.0.1/flow7
        run: |
          pip install pytest
          pytest -q
